  query GetCategories{
    prismic {
      firstData: allCategorys {
        totalCount
        edges {
          cursor
          node {
            _meta {
              uid
            }
            title
            parent_category {
              ... on PRISMIC_Category {
                title
                _meta {
                  uid
                }
              }
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
      lastData: allCategorys(after: "YXJyYXljb25uZWN0aW9uOjE5") {
        totalCount
        edges {
          cursor
          node {
            _meta {
              uid
            }
            title
            parent_category {
              ... on PRISMIC_Category {
                title
                _meta {
                  uid
                }
              }
            }
          }
        }
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
`;